In [1]:
#1.creat an array
import numpy as np

creat_array=np.array([1,2,3,4,5])

print("Creat_array:",creat_array)


Creat_array: [1 2 3 4 5]


In [ ]:
#2.creat_arange_array
import numpy as np

range_array=np.arange(1,20,2)

print("Arrange_array:",range_array)

Arrange_array: [ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#3.Evenly spaced numbers between 0 and 1 (5 values)
import numpy as np

Spaced_number=np.linspace(0,1,3)

print("Spaced_numbers:",Spaced_number.astype(float))

Spaced_numbers: [0.  0.5 1. ]


In [3]:
#4.2×3 matrix filled with 0
import numpy as np

matrix_fill=np.zeros([3*2])

print("matrix:",matrix_fill)

matrix: [0. 0. 0. 0. 0. 0.]


In [ ]:
#5.np.mutmul 
import numpy as np

array1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

arrary2=np.array([[[1,3,5],[2,4,6],[7,9,11]]])

array3=np.matmul(array1,arrary2)

print("matmul:\n",array3)

matmul:
 [[[ 26  38  50]
  [ 56  86 116]
  [ 86 134 182]]]


In [ ]:
#6.np.ones((3,3)) 3*3 matrix filled with 1
import numpy as np

matrix_one=np.ones((3,3))

print("matrix_1:\n",matrix_one)

matrix_1:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#7.Identity matrix (3×3)
import numpy as np

mat_3=np.eye(4)

print(mat_3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#8.arange_array
import numpy as np

arange_array=np.arange(10)

print("Arrange_array:",arange_array)

Arrange_array: [0 1 2 3 4 5 6 7 8 9]


In [19]:
#9.reshape_array
import numpy as np

arr = np.arange(25)       # [0 1 2 3 4 5]

reshaped = np.reshape(arr, (5, 5))
print(reshaped)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
